default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    host: <%= ENV['DB_HOST'] || 'altaria.proxy.rlwy.net' %>
    database: <%= ENV['DB_NAME'] || 'railway' %>
    username: <%= ENV['DB_USERNAME'] || 'postgres' %>
    password: <%= ENV['DB_PASSWORD'] || 'avZhBVmlmOfzDzblnoUjUSIXBJTofVms' %>
    port: <%= ENV['DB_PORT'] || 14754 %>
  cable:
    <<: *primary_development
  queue:
    <<: *primary_development
  cache:
    <<: *primary_development

test:
  primary: &primary_test
    <<: *default
    database: atmanirbhar_farm_test
  cable:
    <<: *primary_test
  queue:
    <<: *primary_test
  cache:
    <<: *primary_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:avZhBVmlmOfzDzblnoUjUSIXBJTofVms@altaria.proxy.rlwy.net:14754/railway' %>
    host: <%= ENV['DB_HOST'] || 'altaria.proxy.rlwy.net' %>
    database: <%= ENV['DB_NAME'] || 'railway' %>
    username: <%= ENV['DB_USERNAME'] || 'postgres' %>
    password: <%= ENV['DB_PASSWORD'] || 'avZhBVmlmOfzDzblnoUjUSIXBJTofVms' %>
    port: <%= ENV['DB_PORT'] || 14754 %>
  cable:
    <<: *primary_production
  queue:
    <<: *primary_production
  cache:
    <<: *primary_production